### ISSUE TITLE
Database Error: Duplicate column name 'value-en'

### ISSUE THREAD

**Issue by jurajkapsz** [DeuxHuitHuit/multilingual_checkbox_field#3]
I am getting an error, when just saving Symphony `Preferences`:

    Symphony Fatal Database Error: Duplicate column name 'value-en'

**An error occurred while attempting to execute the following query:**
    
    ALTER TABLE `sym_entries_data_60` ADD COLUMN `handle-en` varchar(255) default NULL,
    ADD COLUMN `value-en` text default NULL, ADD COLUMN `value_formatted-en` text default NULL,
    ADD COLUMN `word_count-en` int(11) default NULL;

**Backtrace:**

    [.../symphony/lib/toolkit/class.mysql.php:554]
    MySQL->__error();
    [.../extensions/multilingual_checkbox_field/extension.driver.php:192]
    MySQL->query();
    [.../symphony/lib/toolkit/class.extensionmanager.php:706]
    Extension_Multilingual_Checkbox_Field->dFLSavePreferences();
    [.../extensions/frontend_localisation/extension.driver.php:331]
    ExtensionManager::notifyMembers();
    [.../symphony/lib/toolkit/class.extensionmanager.php:706]
    Extension_Frontend_Localisation->dSave();
    [.../symphony/content/content.systempreferences.php:216]
    ExtensionManager::notifyMembers();
    [.../symphony/lib/toolkit/class.administrationpage.php:449]
    contentSystemPreferences->action();
    [.../symphony/lib/core/class.administration.php:212]
    AdministrationPage->build();
    [.../symphony/lib/core/class.administration.php:490]
    Administration->__buildPage();
    [.../symphony/lib/boot/func.utilities.php:231]
    Administration->display();
    [.../symphony/lib/boot/func.utilities.php:213]
    symphony_launcher();
    [.../index.php:17]
    symphony();

**Database Query Log:**

    ...
    [0.0010] SHOW COLUMNS FROM `sym_entries_data_60` LIKE 'handle-%';;

**More info:**

This error does not occur, when I don't have any Multilingual Checkbox field assigned yet in any section.

Running latest extension version v1.0.2 with Symphony v2.6.11

**Comment by nitriques** [comment]
Did you:

1) Change languages juste before ?
2) Update any extension lately ?

> This error does not occur, when I don't have any Multilingual Checkbox field assigned yet in any section.

Yup this is normal ;)

**Comment by jurajkapsz** [comment]
> 1. Change languages juste before ?

I don't think so. I had my languages set up and later on just added this extension.

> 2. Update any extension lately ?

I'd updated Text Box field to v2.7, then realized I need to update the Multilingual Text Field too, so I did to v3.5.9 (as of now to v.3.5.10).

For the time being, I have commented out the whole [method](https://github.com/DeuxHuitHuit/multilingual_checkbox_field/blob/master/extension.driver.php#L135) and things go along well.

**Comment by jurajkapsz** [comment]
And, maybe this is also **some other bug**: Now I have tried out to add more languages, and when I try to save an entry, I get an `Symphony Fatal Database Error: Unknown column 'value-cs' in 'field list'` for that language. Where should I report it, or what should I check first?

Thanks.

**Edit:** I could make a clean install of latest Symphony with latest multilingual extensions and test this behaviour, if it helps. I have the latest versions of everything also in my working "buggy" installation, but there are other extensions as well, and I cannot tell what changed where over the time.

**Comment by nitriques** [comment]
>  I have the latest versions of everything also in my working "buggy" installation, 

We all end up with those kind of setups ;)
Hopefully, this will change since you can now install Symphony from a [unattended perspective](https://github.com/symphonycms/symphony-2/pull/2654)

Sadly, the problems comes from a copy/paste without edit... the commit is on its way.

**Comment by nitriques** [comment]
Fixed in `1.0.3`. Thanks!
